name: Add Contributors

on: [ push, pull_request ]

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: To automate contrib in readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}